version: '3.9'

services:
  react-app:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - express-backend
    networks:
      - mern-network

  express-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mern-db
    depends_on:
      - mongodb
    networks:
      - mern-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mern-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - mern-network
    command:
      - "grafana cli plugins update-all && grafana"
    environment:
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-clock-panel

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
