version: '3'

services:
  react-app:
    build:
      context: ./frontend
    ports:
      - "80:80" # React uygulaması 3000 portunda çalışacak, dışarıya 80 portu yönlendirilmiş
    depends_on:
      - express-backend
    networks:
      - mern-network

  express-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mern-db # MongoDB'ye bağlantı servisi adıyla yapılır
    depends_on:
      - mongodb
    networks:
      - mern-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
