global:
  scrape_interval: 15s # Verileri her 15 saniyede bir çek

scrape_configs:
  - job_name: "express-backend"
    static_configs:
      - targets: ["express-backend:5000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
