apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs-app
  template:
    metadata:
      labels:
        app: expressjs-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: expressjs-app
        image: docker.io/aakyuz1/mern_backend:latest
