apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  labels:
    app: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: your-express-image:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password@mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  clusterIP: None
