apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-secret
spec:
  secretStoreRef:
    name: mern-secret   # AWS Secret Store ismini buraya yazın
  target:
    name: ecr-secret        # Kubernetes'teki secret adı
  data:
    - secretKey: ecr-password
      remoteRef:
        key: mern-secret
        property: password
